language: go
sudo: false

os:
  - linux

env:
  - GO111MODULE=on

go:
  - 1.x

script:
  # Windows-386 build
  - GOOS=windows GOARCH=386 VERSION=${TRAVIS_TAG:-dev} make release
  # Windows-amd64 build
  - GOOS=windows GOARCH=amd64 VERSION=${TRAVIS_TAG:-dev} make release
  # Linux-386 build
  - GOOS=linux GOARCH=386 VERSION=${TRAVIS_TAG:-dev} make release
  # Linux-amd64 build
  - GOOS=linux GOARCH=amd64 VERSION=${TRAVIS_TAG:-dev} make release
  # Darwin-amd64 build
  - GOOS=darwin GOARCH=amd64 VERSION=${TRAVIS_TAG:-dev} make release
  # List build output
  - ls -l build/dnslookup-*

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file:
    - build/dnslookup-*.zip
    - build/dnslookup-*.tar.gz
  on:
    repo: ameshkov/dnslookup
    tags: true
  file_glob: true
  skip_cleanup: true